openapi: 3.0.3
info:
  title: Laravel
  description: ''
  version: 1.0.0
servers:
  -
    url: 'http://localhost'
paths:
  /api/user:
    get:
      summary: ''
      operationId: getApiUser
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
      security: []
  /api/tasks:
    get:
      summary: 'Shows all task for a single user'
      operationId: showsAllTaskForASingleUser
      description: ''
      parameters: []
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example: {  }
                properties: {  }
      tags:
        - Web
      security: []
    post:
      summary: 'Creates a new tasks'
      operationId: createsANewTasks
      description: ''
      parameters: []
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example: {  }
                properties: {  }
      tags:
        - Web
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: ''
                  example: maxime
                description:
                  type: string
                  description: ''
                  example: 'Temporibus consequatur ea illo sint reprehenderit possimus.'
                task_status:
                  type: string
                  description: ''
                  example: Completed
                  enum:
                    - Pending
                    - In_progress
                    - Completed
              required:
                - name
                - task_status
      security: []
  '/api/tasks/{id}':
    get:
      summary: 'Fetches a single task by id'
      operationId: fetchesASingleTaskById
      description: ''
      parameters: []
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example: {  }
                properties: {  }
      tags:
        - Web
      security: []
    put:
      summary: 'Edits a task by id'
      operationId: editsATaskById
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Web
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: ''
                  example: harum
                description:
                  type: string
                  description: ''
                  example: 'Asperiores officiis necessitatibus illum repellendus ipsum minima et.'
                task_status:
                  type: string
                  description: ''
                  example: Pending
                  enum:
                    - Pending
                    - In_progress
                    - Completed
              required:
                - name
                - task_status
      security: []
    delete:
      summary: 'Deletes a task'
      operationId: deletesATask
      description: ''
      parameters: []
      responses:
        204:
          description: ''
      tags:
        - Web
      security: []
    parameters:
      -
        in: path
        name: id
        description: 'The ID of the task.'
        example: 17
        required: true
        schema:
          type: integer
tags:
  -
    name: Endpoints
    description: ''
  -
    name: Web
    description: ''
